name: customer_io_web
description: Web implementation of the customer_io plugin.
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  dio: ^5.7.0
  js: ^0.6.5


flutter:
  plugin:
    implements: customer_io
    platforms:
      web:
        pluginClass: CustomerIOWebPlugin
        fileName: customer_io_web.dart

